### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by czifro** [irium/FsSql#1]
I'd like to offer my support as a contributor to help maintain, address bugs, and potentially add features to it in any spare time I have. Mausch had some interesting ideas that could improve usability: https://github.com/mausch/FsSql/issues/10, https://github.com/mausch/FsSql/issues/8, etc. There are some apparent bugs as well: https://github.com/mausch/FsSql/issues/28, https://github.com/mausch/FsSql/issues/13, etc. I would be willing to address some of these when I get time.

I see in your PR you mentioned not having a Linux environment to test off of. The closest I have to that is MacOS. Unless it is something very specific to Linux, I believe I can help with more general *nix testing.

Lastly, thanks for porting this to NET Core 2.0, it has been a tremendous help with my work.

Cheers!

**Comment by irium** [comment]
Thank you! Feel free to fix any bugs and send any PRs you want. I'm not a real owner, nor a maitainer of the repo. I just have seen this project and found that this is what I need, but on .NET Core. So I just ported it (this wasn't too hard to be honest :) and published to NuGet after @haf asked me.

First of all I recommend to port @haf 's changes about namespaces to here.
See commits from https://github.com/haf/FsSql/tree/feature/namespaces-logging branch.

**Comment by czifro** [comment]
That seems simple enough to get started. I also think that the build process could be improved. Docker could be used to run the FAKE script so that there is a consistent environment to run tests and create packages, which could be helpful for using a CI system.

**Comment by haf** [comment]
Feel free to take what you need from @suaveio and @logary's build scripts

**Comment by czifro** [comment]
Thanks for the references.

**Comment by irium** [comment]
@czifro Please don't do Docker *the only* way to run tests :)

**Comment by czifro** [comment]
You got it! I will just set it up so that it is an option. So to recap, there will be the following methods:

1. build.dat
2. build.sh -- needs adjustments
3. docker-build.bat -- may need help with testing the script, I don't have a Windows machine
4. docker-build.sh

If this seems ok, I can work on it in my spare time.
